easy_admin:
    design:
        menu:
            -
                label: 'System'
                roles: ['ROLE_SUPER_ADMIN']
                children:
                    - { label: 'Dump Database', route: 'krg_orm_admin_download', icon: 'database' }
