services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $enumTypes: '%doctrine.dbal.connection_factory.types%'
            $locale: '%locale%'

    KRG\DoctrineExtensionBundle\Form\Type\:
        resource: '../../Form/Type'
        tags: ['form.type']
        public: true

    KRG\DoctrineExtensionBundle\Form\Extension\EntityTypeExtension:
        public: true
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    KRG\DoctrineExtensionBundle\Form\Extension\ChoiceTypeExtension:
        public: true
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }
            
    KRG\DoctrineExtensionBundle\Form\Extension\HiddenTypeExtension:
        public: true
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\HiddenType }

    KRG\DoctrineExtensionBundle\Form\Extension\EasyAdminEntityTypeExtension:
        public: true
        tags:
            - { name: form.type_extension, extended_type: Symfony\Bridge\Doctrine\Form\Type\EntityType }

    KRG\DoctrineExtensionBundle\Request\ParamConverter\DoctrineParamConverter:
        decorates: sensio_framework_extra.converter.doctrine.orm
        arguments:
            $doctrineParamConverter: '@KRG\DoctrineExtensionBundle\Request\ParamConverter\DoctrineParamConverter.inner'

    KRG\DoctrineExtensionBundle\Form\TypeGuesser\:
        resource: '../../Form/TypeGuesser'
        tags: ['form.type_guesser']

    KRG\DoctrineExtensionBundle\ORM\EntityManagerDecorator:
        public: false
        decorates: 'Doctrine\ORM\EntityManagerInterface'
        arguments: ['@KRG\DoctrineExtensionBundle\ORM\EntityManagerDecorator.inner']

    KRG\DoctrineExtensionBundle\Listener\:
        resource: '../../Listener/*'
        lazy: true
        tags: [doctrine.event_subscriber]