services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $enumTypes: '%doctrine.dbal.connection_factory.types%'

    KRG\DoctrineExtensionBundle\Form\Type\:
        resource: '../../Form/Type'
        tags: ['form.type']
        public: true

    KRG\DoctrineExtensionBundle\Form\Extension\ChoiceTypeExtension:
        public: true
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

    KRG\DoctrineExtensionBundle\Form\Extension\EasyAdminEntityTypeExtension:
        public: true
        tags:
            - { name: form.type_extension, extended_type: Symfony\Bridge\Doctrine\Form\Type\EntityType }

    KRG\DoctrineExtensionBundle\Request\ParamConverter\DoctrineParamConverter:
        tags:
            - { name: request.param_converter, converter: krg.doctrine.param_converter }
